import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const books = sqliteTable("books", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  subtitle: text("subtitle"),
  author: text("author").notNull(),
  series: text("series"),
  category: text("category").notNull(),
  color: text("color").notNull(),
  isbn: text("isbn"),
  isbn10: text("isbn10"),
  isbn13: text("isbn13"),
  publisher: text("publisher"),
  publishedDate: text("published_date"),
  description: text("description"),
  pageCount: integer("page_count"),
  language: text("language"),
  metadataSource: text("metadata_source"),
  recognitionMethod: text("recognition_method"),
  recognitionConfidence: integer("recognition_confidence"),
  frontImageKey: text("front_image_key"),
  backImageKey: text("back_image_key"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
